name: CI

# We can specify which GitHub events will trigger a CI build
on: [push, pull_request]

# Next we define a single job 'build', but we could add more
jobs:

  build:

    # We can also specify which operating systems we want to test on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # We can use 'run' to execute commands
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .

    - name: Test with PyTest
      run: |
        pytest --cov=inflammation.models tests/test_models.py
